"""
Clinical War Room - Report Generator

Deterministic tool for generating structured case summaries.
NO LLM usage. Template-based formatting only.
"""

from dataclasses import dataclass
from typing import Dict, Any, List, Optional
from datetime import datetime


@dataclass
class ReportSection:
    """A section of the report."""
    title: str
    content: str
    severity: str = "info"  # info, warning, critical


@dataclass
class CaseReport:
    """Structured case report."""
    case_id: str
    patient_id: str
    report_type: str
    generated_at: str
    sections: List[ReportSection]
    summary: str
    risk_level: str
    data_quality_warning: Optional[str]
    
    def to_dict(self) -> dict:
        return {
            "case_id": self.case_id,
            "patient_id": self.patient_id,
            "report_type": self.report_type,
            "generated_at": self.generated_at,
            "sections": [
                {"title": s.title, "content": s.content, "severity": s.severity}
                for s in self.sections
            ],
            "summary": self.summary,
            "risk_level": self.risk_level,
            "data_quality_warning": self.data_quality_warning,
        }
    
    def to_text(self) -> str:
        """Generate human-readable text report."""
        lines = [
            "=" * 60,
            f"CLINICAL GAIT ANALYSIS REPORT",
            "=" * 60,
            f"Case ID: {self.case_id}",
            f"Patient ID: {self.patient_id}",
            f"Report Type: {self.report_type}",
            f"Generated: {self.generated_at}",
            "-" * 60,
        ]
        
        if self.data_quality_warning:
            lines.extend([
                "⚠️  DATA QUALITY WARNING:",
                f"    {self.data_quality_warning}",
                "-" * 60,
            ])
        
        for section in self.sections:
            severity_marker = ""
            if section.severity == "warning":
                severity_marker = "⚠️  "
            elif section.severity == "critical":
                severity_marker = "🔴 "
            
            lines.append(f"\n{severity_marker}{section.title}")
            lines.append("-" * len(section.title))
            lines.append(section.content)
        
        lines.extend([
            "",
            "=" * 60,
            f"OVERALL RISK LEVEL: {self.risk_level.upper()}",
            "=" * 60,
            "",
            "SUMMARY:",
            self.summary,
            "",
            "-" * 60,
            "This report is generated by automated analysis.",
            "Clinical judgment is always required.",
            "-" * 60,
        ])
        
        return "\n".join(lines)


def _format_gait_features_section(gait_features: Dict[str, Any]) -> ReportSection:
    """Format gait features into a report section."""
    cadence = gait_features.get("cadence", 0)
    stride_length = gait_features.get("stride_length", 0)
    gait_speed = gait_features.get("gait_speed", 0)
    asymmetry = gait_features.get("asymmetry_index", 0)
    variability = gait_features.get("variability", 0)
    step_count = gait_features.get("step_count", 0)
    
    content = f"""
Cadence:           {cadence:.1f} steps/min
Stride Length:     {stride_length:.3f} m
Gait Speed:        {gait_speed:.2f} m/s
Asymmetry Index:   {asymmetry:.3f} (0 = symmetric)
Step Variability:  {variability:.3f} (coefficient of variation)
Total Steps:       {step_count}
""".strip()
    
    # Determine severity
    severity = "info"
    if asymmetry > 0.2 or variability > 0.1:
        severity = "warning"
    if asymmetry > 0.3 or variability > 0.15:
        severity = "critical"
    
    return ReportSection(
        title="Gait Parameters",
        content=content,
        severity=severity,
    )


def _format_data_quality_section(quality: Dict[str, Any]) -> ReportSection:
    """Format data quality metrics into a report section."""
    missing = quality.get("missing_data_percentage", 0)
    noise = quality.get("noise_score", 0)
    reliability = quality.get("reliability_score", 0)
    issues = quality.get("issues", [])
    
    content = f"""
Data Reliability:    {reliability:.0%}
Missing Data:        {missing:.1f}%
Noise Level:         {noise:.0%}
""".strip()
    
    if issues:
        content += "\n\nIssues Detected:"
        for issue in issues:
            content += f"\n  • {issue}"
    
    severity = "info"
    if reliability < 0.7:
        severity = "warning"
    if reliability < 0.5:
        severity = "critical"
    
    return ReportSection(
        title="Data Quality Assessment",
        content=content,
        severity=severity,
    )


def _format_fall_risk_section(risk: Dict[str, Any]) -> ReportSection:
    """Format fall risk assessment into a report section."""
    probability = risk.get("fall_risk_probability", 0)
    level = risk.get("risk_level", "unknown")
    factors = risk.get("contributing_factors", [])
    protective = risk.get("protective_factors", [])
    confidence = risk.get("confidence", 0)
    
    content = f"""
Fall Risk Probability: {probability:.0%}
Risk Level:            {level.upper()}
Prediction Confidence: {confidence:.0%}
""".strip()
    
    if factors:
        content += "\n\nRisk Factors:"
        for factor in factors:
            content += f"\n  • {factor}"
    
    if protective:
        content += "\n\nProtective Factors:"
        for factor in protective:
            content += f"\n  ✓ {factor}"
    
    severity = "info"
    if level in ["moderate", "high"]:
        severity = "warning"
    if level == "critical":
        severity = "critical"
    
    return ReportSection(
        title="Fall Risk Assessment",
        content=content,
        severity=severity,
    )


def _format_patient_info_section(patient: Dict[str, Any]) -> ReportSection:
    """Format patient information into a report section."""
    age = patient.get("age", "Unknown")
    sex = patient.get("sex", "Unknown")
    history = patient.get("medical_history", [])
    medications = patient.get("current_medications", [])
    
    content = f"""
Age: {age}
Sex: {sex}
""".strip()
    
    if history:
        content += "\n\nMedical History:"
        for condition in history[:5]:  # Limit to 5
            content += f"\n  • {condition}"
    
    if medications:
        content += "\n\nCurrent Medications:"
        for med in medications[:5]:  # Limit to 5
            content += f"\n  • {med}"
    
    return ReportSection(
        title="Patient Information",
        content=content,
        severity="info",
    )


def _generate_summary(
    risk_level: str,
    risk_probability: float,
    reliability: float,
) -> str:
    """Generate a concise summary statement."""
    if reliability < 0.5:
        quality_note = "Data quality is insufficient for reliable analysis. "
    elif reliability < 0.7:
        quality_note = "Data quality is marginal. Results should be interpreted with caution. "
    else:
        quality_note = ""
    
    if risk_level == "low":
        risk_note = f"Based on the gait analysis, fall risk appears LOW ({risk_probability:.0%} probability)."
    elif risk_level == "moderate":
        risk_note = f"Gait analysis indicates MODERATE fall risk ({risk_probability:.0%} probability). Consider further evaluation."
    elif risk_level == "high":
        risk_note = f"Gait analysis indicates HIGH fall risk ({risk_probability:.0%} probability). Intervention recommended."
    elif risk_level == "critical":
        risk_note = f"Gait analysis indicates CRITICAL fall risk ({risk_probability:.0%} probability). Immediate intervention strongly recommended."
    else:
        risk_note = "Insufficient data to determine fall risk. Additional assessment required."
    
    return quality_note + risk_note


def generate_report(
    case_id: str,
    patient_id: str,
    patient_info: Dict[str, Any],
    gait_features: Optional[Dict[str, Any]] = None,
    data_quality: Optional[Dict[str, Any]] = None,
    fall_risk: Optional[Dict[str, Any]] = None,
) -> CaseReport:
    """
    Generate a structured clinical report from computed metrics.
    
    Args:
        case_id: Unique case identifier
        patient_id: Patient identifier
        patient_info: Patient demographic and history data
        gait_features: Output from gait feature extractor
        data_quality: Output from data quality checker
        fall_risk: Output from fall risk model
        
    Returns:
        CaseReport with formatted sections
    """
    sections = []
    
    # Patient information section
    sections.append(_format_patient_info_section(patient_info))
    
    # Data quality section (if available)
    data_quality_warning = None
    if data_quality:
        sections.append(_format_data_quality_section(data_quality))
        reliability = data_quality.get("reliability_score", 1.0)
        if reliability < 0.5:
            data_quality_warning = "Data quality is poor. Results may be unreliable."
    
    # Gait features section (if available)
    if gait_features:
        sections.append(_format_gait_features_section(gait_features))
    
    # Fall risk section (if available)
    if fall_risk:
        sections.append(_format_fall_risk_section(fall_risk))
    
    # Determine overall risk level
    if fall_risk:
        risk_level = fall_risk.get("risk_level", "unknown")
        risk_probability = fall_risk.get("fall_risk_probability", 0)
    else:
        risk_level = "unknown"
        risk_probability = 0
    
    # Generate summary
    reliability = data_quality.get("reliability_score", 1.0) if data_quality else 1.0
    summary = _generate_summary(risk_level, risk_probability, reliability)
    
    return CaseReport(
        case_id=case_id,
        patient_id=patient_id,
        report_type="Gait Analysis and Fall Risk Assessment",
        generated_at=datetime.utcnow().isoformat(),
        sections=sections,
        summary=summary,
        risk_level=risk_level,
        data_quality_warning=data_quality_warning,
    )
